namespace KeyboardHook
{
    public class KeyboardKey
    {
        /// <summary>
        /// Convert  Win32 Virtual-Key to WPF Key
        /// </summary>
        /// <param name="virtualKey">The virtual key to be converted.</param>
        /// <returns>Key:WPF Key</returns>
        public static Key KeyFromVirtualKey(int virtualKey)
        {
            return virtualKey switch
            {
                3 => Key.Cancel,
                8 => Key.Back,
                9 => Key.Tab,
                12 => Key.Clear,
                13 => Key.Return,
                19 => Key.Pause,
                20 => Key.Capital,
                21 => Key.KanaMode,
                23 => Key.JunjaMode,
                24 => Key.FinalMode,
                25 => Key.HanjaMode,
                27 => Key.Escape,
                28 => Key.ImeConvert,
                29 => Key.ImeNonConvert,
                30 => Key.ImeAccept,
                31 => Key.ImeModeChange,
                32 => Key.Space,
                33 //=> Key.Prior,
                   => Key.PageUp,
                34 //=> Key.Next,
                   => Key.PageDown,
                35 => Key.End,
                36 => Key.Home,
                37 => Key.Left,
                38 => Key.Up,
                39 => Key.Right,
                40 => Key.Down,
                41 => Key.Select,
                42 => Key.Print,
                43 => Key.Execute,
                //44 => Key.Snapshot,
                44 => Key.PrintScreen,
                45 => Key.Insert,
                46 => Key.Delete,
                47 => Key.Help,
                48 => Key.D0,
                49 => Key.D1,
                50 => Key.D2,
                51 => Key.D3,
                52 => Key.D4,
                53 => Key.D5,
                54 => Key.D6,
                55 => Key.D7,
                56 => Key.D8,
                57 => Key.D9,
                65 => Key.A,
                66 => Key.B,
                67 => Key.C,
                68 => Key.D,
                69 => Key.E,
                70 => Key.F,
                71 => Key.G,
                72 => Key.H,
                73 => Key.I,
                74 => Key.J,
                75 => Key.K,
                76 => Key.L,
                77 => Key.M,
                78 => Key.N,
                79 => Key.O,
                80 => Key.P,
                81 => Key.Q,
                82 => Key.R,
                83 => Key.S,
                84 => Key.T,
                85 => Key.U,
                86 => Key.V,
                87 => Key.W,
                88 => Key.X,
                89 => Key.Y,
                90 => Key.Z,
                91 => Key.LWin,
                92 => Key.RWin,
                93 => Key.Apps,
                95 => Key.Sleep,
                96 => Key.NumPad0,
                97 => Key.NumPad1,
                98 => Key.NumPad2,
                99 => Key.NumPad3,
                100 => Key.NumPad4,
                101 => Key.NumPad5,
                102 => Key.NumPad6,
                103 => Key.NumPad7,
                104 => Key.NumPad8,
                105 => Key.NumPad9,
                106 => Key.Multiply,
                107 => Key.Add,
                108 => Key.Separator,
                109 => Key.Subtract,
                110 => Key.Decimal,
                111 => Key.Divide,
                112 => Key.F1,
                113 => Key.F2,
                114 => Key.F3,
                115 => Key.F4,
                116 => Key.F5,
                117 => Key.F6,
                118 => Key.F7,
                119 => Key.F8,
                120 => Key.F9,
                121 => Key.F10,
                122 => Key.F11,
                123 => Key.F12,
                124 => Key.F13,
                125 => Key.F14,
                126 => Key.F15,
                127 => Key.F16,
                128 => Key.F17,
                129 => Key.F18,
                130 => Key.F19,
                131 => Key.F20,
                132 => Key.F21,
                133 => Key.F22,
                134 => Key.F23,
                135 => Key.F24,
                144 => Key.NumLock,
                145 => Key.Scroll,
                16 => Key.LeftShift,
                160 => Key.LeftShift,
                161 => Key.RightShift,
                17 => Key.LeftCtrl,
                162 => Key.LeftCtrl,
                163 => Key.RightCtrl,
                18 => Key.LeftAlt,
                164 => Key.LeftAlt,
                165 => Key.RightAlt,
                166 => Key.BrowserBack,
                167 => Key.BrowserForward,
                168 => Key.BrowserRefresh,
                169 => Key.BrowserStop,
                170 => Key.BrowserSearch,
                171 => Key.BrowserFavorites,
                172 => Key.BrowserHome,
                173 => Key.VolumeMute,
                174 => Key.VolumeDown,
                175 => Key.VolumeUp,
                176 => Key.MediaNextTrack,
                177 => Key.MediaPreviousTrack,
                178 => Key.MediaStop,
                179 => Key.MediaPlayPause,
                180 => Key.LaunchMail,
                181 => Key.SelectMedia,
                182 => Key.LaunchApplication1,
                183 => Key.LaunchApplication2,
                186 => Key.Oem1,
                187 => Key.OemPlus,
                188 => Key.OemComma,
                189 => Key.OemMinus,
                190 => Key.OemPeriod,
                191 => Key.Oem2,
                192 => Key.Oem3,
                193 => Key.AbntC1,
                194 => Key.AbntC2,
                219 => Key.Oem4,
                220 => Key.Oem5,
                221 => Key.Oem6,
                222 => Key.Oem7,
                223 => Key.Oem8,
                226 => Key.Oem102,
                229 => Key.ImeProcessed,
                240 => Key.OemAttn,
                241 => Key.OemFinish,
                242 => Key.OemCopy,
                243 => Key.OemAuto,
                244 => Key.OemEnlw,
                245 => Key.OemBackTab,
                246 => Key.Attn,
                247 => Key.CrSel,
                248 => Key.ExSel,
                249 => Key.EraseEof,
                250 => Key.Play,
                251 => Key.Zoom,
                252 => Key.NoName,
                253 => Key.Pa1,
                254 => Key.OemClear,
                _ => Key.None
            };
        }

        /// <summary>
        /// Convert WPF Key to Win32 Virtual-Key
        /// </summary>
        /// <param name="key">WPF Key</param>
        /// <returns>int:The virtual key to be converted.</returns>
        public static int VirtualKeyFromKey(Key key)
        {
            return key switch
            {
                Key.Cancel => 3,
                Key.Back => 8,
                Key.Tab => 9,
                Key.Clear => 12,
                Key.Return => 13,
                Key.Pause => 19,
                Key.Capital => 20,
                Key.KanaMode => 21,
                Key.JunjaMode => 23,
                Key.FinalMode => 24,
                Key.HanjaMode => 25,
                Key.Escape => 27,
                Key.ImeConvert => 28,
                Key.ImeNonConvert => 29,
                Key.ImeAccept => 30,
                Key.ImeModeChange => 31,
                Key.Space => 32,
                //Key.Prior => 33,
                Key.PageUp => 33,
                //Key.Next => 34,
                Key.PageDown => 34,
                Key.End => 35,
                Key.Home => 36,
                Key.Left => 37,
                Key.Up => 38,
                Key.Right => 39,
                Key.Down => 40,
                Key.Select => 41,
                Key.Print => 42,
                Key.Execute => 43,
                Key.Snapshot => 44,
                //Key.PrintScreen => 44,
                Key.Insert => 45,
                Key.Delete => 46,
                Key.Help => 47,
                Key.D0 => 48,
                Key.D1 => 49,
                Key.D2 => 50,
                Key.D3 => 51,
                Key.D4 => 52,
                Key.D5 => 53,
                Key.D6 => 54,
                Key.D7 => 55,
                Key.D8 => 56,
                Key.D9 => 57,
                Key.A => 65,
                Key.B => 66,
                Key.C => 67,
                Key.D => 68,
                Key.E => 69,
                Key.F => 70,
                Key.G => 71,
                Key.H => 72,
                Key.I => 73,
                Key.J => 74,
                Key.K => 75,
                Key.L => 76,
                Key.M => 77,
                Key.N => 78,
                Key.O => 79,
                Key.P => 80,
                Key.Q => 81,
                Key.R => 82,
                Key.S => 83,
                Key.T => 84,
                Key.U => 85,
                Key.V => 86,
                Key.W => 87,
                Key.X => 88,
                Key.Y => 89,
                Key.Z => 90,
                Key.LWin => 91,
                Key.RWin => 92,
                Key.Apps => 93,
                Key.Sleep => 95,
                Key.NumPad0 => 96,
                Key.NumPad1 => 97,
                Key.NumPad2 => 98,
                Key.NumPad3 => 99,
                Key.NumPad4 => 100,
                Key.NumPad5 => 101,
                Key.NumPad6 => 102,
                Key.NumPad7 => 103,
                Key.NumPad8 => 104,
                Key.NumPad9 => 105,
                Key.Multiply => 106,
                Key.Add => 107,
                Key.Separator => 108,
                Key.Subtract => 109,
                Key.Decimal => 110,
                Key.Divide => 111,
                Key.F1 => 112,
                Key.F2 => 113,
                Key.F3 => 114,
                Key.F4 => 115,
                Key.F5 => 116,
                Key.F6 => 117,
                Key.F7 => 118,
                Key.F8 => 119,
                Key.F9 => 120,
                Key.F10 => 121,
                Key.F11 => 122,
                Key.F12 => 123,
                Key.F13 => 124,
                Key.F14 => 125,
                Key.F15 => 126,
                Key.F16 => 127,
                Key.F17 => 128,
                Key.F18 => 129,
                Key.F19 => 130,
                Key.F20 => 131,
                Key.F21 => 132,
                Key.F22 => 133,
                Key.F23 => 134,
                Key.F24 => 135,
                Key.NumLock => 144,
                Key.Scroll => 145,
                Key.LeftShift => 160,
                Key.RightShift => 161,
                Key.LeftCtrl => 162,
                Key.RightCtrl => 163,
                Key.LeftAlt => 164,
                Key.RightAlt => 165,
                Key.BrowserBack => 166,
                Key.BrowserForward => 167,
                Key.BrowserRefresh => 168,
                Key.BrowserStop => 169,
                Key.BrowserSearch => 170,
                Key.BrowserFavorites => 171,
                Key.BrowserHome => 172,
                Key.VolumeMute => 173,
                Key.VolumeDown => 174,
                Key.VolumeUp => 175,
                Key.MediaNextTrack => 176,
                Key.MediaPreviousTrack => 177,
                Key.MediaStop => 178,
                Key.MediaPlayPause => 179,
                Key.LaunchMail => 180,
                Key.SelectMedia => 181,
                Key.LaunchApplication1 => 182,
                Key.LaunchApplication2 => 183,
                Key.Oem1 => 186,
                Key.OemPlus => 187,
                Key.OemComma => 188,
                Key.OemMinus => 189,
                Key.OemPeriod => 190,
                Key.Oem2 => 191,
                Key.Oem3 => 192,
                Key.AbntC1 => 193,
                Key.AbntC2 => 194,
                Key.Oem4 => 219,
                Key.Oem5 => 220,
                Key.Oem6 => 221,
                Key.Oem7 => 222,
                Key.Oem8 => 223,
                Key.Oem102 => 226,
                Key.ImeProcessed => 229,
                Key.OemAttn => 240,
                Key.OemFinish => 241,
                Key.OemCopy => 242,
                Key.OemAuto => 243,
                Key.OemEnlw => 244,
                Key.OemBackTab => 245,
                Key.Attn => 246,
                Key.CrSel => 247,
                Key.ExSel => 248,
                Key.EraseEof => 249,
                Key.Play => 250,
                Key.Zoom => 251,
                Key.NoName => 252,
                Key.Pa1 => 253,
                Key.OemClear => 254,
                Key.DeadCharProcessed => 0,
                _ => 0,
            };
        }

        /// <summary>
        /// WPF Key enumeration
        /// </summary>
        public enum Key
        {
            None = 0,           //	不按任何键。
            Cancel = 1,         //	Cancel 键。
            Back = 2,           //	Backspace 键。
            Tab = 3,            //	Tab 键。
            LineFeed = 4,       //	Linefeed 键。
            Clear = 5,          //  Clear 键。清除
            Return = 6,         //  Return 键。
            Enter = 6,          //  Enter 键。
            Pause = 7,          //  Pause 键,中断暂停键。
            Capital = 8,        //	Caps Lock 键。
            CapsLock = 8,       //	Caps Lock 键。
            KanaMode = 9,       //	IME Kana 模式键。 日语输入法
            HangulMode = 9,     //	IME Hangul 模式键。韩语输入法
            JunjaMode = 10,     //	IME Junja 模式键。 Junja 是构成韩国写作系统的一部分的音节
            FinalMode = 11,     //  IME Final 模式键。
            HanjaMode = 12,     //	IME Hanja 模式键。
            KanjiMode = 12,     //  IME Kanji 模式键。
            Escape = 13,        //	ESC 键。
            ImeConvert = 14,    //	IME Convert 键。
            ImeNonConvert = 15, //  IME NonConvert 键。
            ImeAccept = 16,     //	IME Accept 键。
            ImeModeChange = 17, //	IME 模式更改请求。
            Space = 18,         //	Spacebar 键。

            //Prior = 19,       //	Page Up 键。
            PageUp = 19,        //	Page Up 键。

            //Next = 20,        //	Page Down 键。
            PageDown = 20,      //	Page Down 键。

            End = 21,           //	End 键。
            Home = 22,          //	Home 键。
            Left = 23,          //	Left Arrow 键。
            Up = 24,            //	Up Arrow 键。
            Right = 25,         //	Right Arrow 键。
            Down = 26,          //	Down Arrow 键。
            Select = 27,        //	Select 键。
            Print = 28,         //	Print 键。
            Execute = 29,       //	Execute 键。
            Snapshot = 30,      //	Print Screen 键。
            PrintScreen = 30,   //	Print Screen 键。
            Insert = 31,
            Delete = 32,
            Help = 33,
            D0 = 34,   //	0 （零）键。
            D1 = 35,   //	1 （一）键。
            D2 = 36,   //	2 键。
            D3 = 37,   //	3 键。
            D4 = 38,   //	4 键。
            D5 = 39,   //	5 键。
            D6 = 40,   //	6 键。
            D7 = 41,   //	7 键。
            D8 = 42,   //	8 键。
            D9 = 43,   //	9 键。
            A = 44,
            B = 45,
            C = 46,
            D = 47,
            E = 48,
            F = 49,
            G = 50,
            H = 51,
            I = 52,
            J = 53,
            K = 54,
            L = 55,
            M = 56,
            N = 57,
            O = 58,
            P = 59,
            Q = 60,
            R = 61,
            S = 62,
            T = 63,
            U = 64,
            V = 65,
            W = 66,
            X = 67,
            Y = 68,
            Z = 69,
            LWin = 70,             //	左 Windows 徽标键 (Microsoft Natural Keyboard)。
            RWin = 71,             //	右 Windows 徽标键(Microsoft Natural Keyboard)。
            Apps = 72,             //   应用程序键(Microsoft Natural Keyboard)。 也称为菜单键，因为它显示特定于应用程序的上下文菜单。
            Sleep = 73,            //   计算机休眠键。
            NumPad0 = 74,          //   数字键盘上的 0 键。
            NumPad1 = 75,          //	数字键盘上的 1 键。
            NumPad2 = 76,          //	数字键盘上的 2 键。
            NumPad3 = 77,          //	数字键盘上的 3 键。
            NumPad4 = 78,          //	数字键盘上的 4 键。
            NumPad5 = 79,          //	数字键盘上的 5 键。
            NumPad6 = 80,          //	数字键盘上的 6 键。
            NumPad7 = 81,          //	数字键盘上的 7 键。
            NumPad8 = 82,          //	数字键盘上的 8 键。
            NumPad9 = 83,          //	数字键盘上的 9 键。
            Multiply = 84,         //	乘号键。
            Add = 85,              //	加号键。
            Separator = 86,        //	分隔符键。
            Subtract = 87,         //	减号键。
            Decimal = 88,          //   句点键。
            Divide = 89,           //	除号键。
            F1 = 90,
            F2 = 91,
            F3 = 92,
            F4 = 93,
            F5 = 94,
            F6 = 95,
            F7 = 96,
            F8 = 97,
            F9 = 98,
            F10 = 99,
            F11 = 100,
            F12 = 101,
            F13 = 102,
            F14 = 103,
            F15 = 104,
            F16 = 105,
            F17 = 106,
            F18 = 107,
            F19 = 108,
            F20 = 109,
            F21 = 110,
            F22 = 111,
            F23 = 112,
            F24 = 113,
            NumLock = 114,              //	Num Lock 键。
            Scroll = 115,               //	Scroll Lock 键。
            LeftShift = 116,
            RightShift = 117,
            LeftCtrl = 118,
            RightCtrl = 119,
            LeftAlt = 120,
            RightAlt = 121,
            BrowserBack = 122,          //	浏览器后退键。
            BrowserForward = 123,       //	浏览器前进键。
            BrowserRefresh = 124,       //	浏览器刷新键。
            BrowserStop = 125,          //	浏览器停止键。
            BrowserSearch = 126,        //	浏览器搜索键。
            BrowserFavorites = 127,     //	浏览器收藏键。
            BrowserHome = 128,          //	浏览器主页键。
            VolumeMute = 129,           //	静音键。
            VolumeDown = 130,           //	音量减小键。
            VolumeUp = 131,             //	音量增大键。
            MediaNextTrack = 132,       //	媒体下一曲目键。
            MediaPreviousTrack = 133,   //	媒体上一曲目键。
            MediaStop = 134,            //	媒体停止键。
            MediaPlayPause = 135,       //	媒体暂停播放键。
            LaunchMail = 136,           //	启动邮件键。
            SelectMedia = 137,          //	选择媒体键。
            LaunchApplication1 = 138,   //	启动应用程序 1 键。
            LaunchApplication2 = 139,   //	启动应用程序 2 键。
            Oem1 = 140,                 //	OEM 1 键。
            OemSemicolon = 140,         //	OEM 分号键。
            OemPlus = 141,              //	OEM 加号键。
            OemComma = 142,             //	OEM 逗号键。
            OemMinus = 143,             //	OEM 减号键。
            OemPeriod = 144,            //	OEM 句号键。
            Oem2 = 145,                 //	OEM 2 键。
            OemQuestion = 145,          //	OEM 问号键。
            Oem3 = 146,                 //	OEM 3 键。
            OemTilde = 146,             //	OEM 颚化符键。
            AbntC1 = 147,
            AbntC2 = 148,
            Oem4 = 149,                 //	OEM 4 键。
            OemOpenBrackets = 149,      //	OEM 左大括号键。
            Oem5 = 150,                 //	OEM 5 键。
            OemPipe = 150,              //	OEM 管道键。
            Oem6 = 151,                 //	OEM 6 键。
            OemCloseBrackets = 151,     //	OEM 右大括号键。
            Oem7 = 152,                 //	OEM 7 键。
            OemQuotes = 152,            //	OEM 引号键。
            Oem8 = 153,                 //	OEM 8 键。
            Oem102 = 154,               //	OEM 102 键。
            OemBackslash = 154,         //	OEM 反斜杠键。
            ImeProcessed = 155,         //	用于屏蔽 IME 正在处理的真实键的特殊键。
            System = 156,               //	用于屏蔽作为系统键处理的真实键的特殊键。
            OemAttn = 157,              //	OEM ATTN 键。
            DbeAlphanumeric = 157,      //	DBE_ALPHANUMERIC 键。
            OemFinish = 158,            //	OEM FINISH 键。
            DbeKatakana = 158,          //	DBE_KATAKANA 键。
            OemCopy = 159,              //	OEM COPY 键。
            DbeHiragana = 159,          // DBE_HIRAGANA 键。
            OemAuto = 160,              // OEM AUTO 键。
            DbeSbcsChar = 160,          // DBE_SBCSCHAR 键。
            OemEnlw = 161,              // OEM ENLW 键。
            DbeDbcsChar = 161,          // DBE_DBCSCHAR 键。
            OemBackTab = 162,           // OEM BACKTAB 键。
            DbeRoman = 162,             // DBE_ROMAN 键。
            Attn = 163,                 // ATTN 键。
            DbeNoRoman = 163,           // DBE_NOROMAN 键。
            CrSel = 164,                // CRSEL 键。
            DbeEnterWordRegisterMode = 164,     //	DBE_ENTERWORDREGISTERMODE 键。
            ExSel = 165,                        //	EXSEL 键。
            DbeEnterImeConfigureMode = 165,     //	DBE_ENTERIMECONFIGMODE 键。
            EraseEof = 166,                     //	ERASE EOF 键。
            DbeFlushString = 166,               //	DBE_FLUSHSTRING 键。
            Play = 167,                         //	播放键。
            DbeCodeInput = 167,                 // DBE_CODEINPUT 键。
            Zoom = 168,                         // 缩放键。
            DbeNoCodeInput = 168,               // DBE_NOCODEINPUT 键。
            NoName = 169,                       // 留待将来使用的常数。
            DbeDetermineString = 169,           // DBE_DETERMINESTRING 键。
            Pa1 = 170,                          // PA1 键。
            DbeEnterDialogConversionMode = 170, // DBE_ENTERDLGCONVERSIONMODE 键。
            OemClear = 171,                     // OEM 清除键。
            DeadCharProcessed = 172             // 该键与另一个键配合使用，用于创建单一的组合字符。
        }
    }
}